import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GeneralProvider } from "@/shared/providers/general-provider";
import { PayPalProvider } from "@/shared/providers/PayPalProvider";
import BackgroundCircles from "@/shared/layout/background-circles";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <BackgroundCircles />
        <div className="relative z-[1] min-h-screen">
          <GeneralProvider>
            <PayPalProvider>{children}</PayPalProvider>
          </GeneralProvider>
        </div>
      </body>
    </html>
  );
}
